// <auto-generated />
using System;
using CarDealershipApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarDealershipApp.Data.Migrations
{
    [DbContext(typeof(CarDealershipDbContext))]
    [Migration("20250831203252_seededcars_removed")]
    partial class seededcars_removed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarDealershipApp.Data.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://static.vecteezy.com/system/resources/thumbnails/020/927/378/small_2x/toyota-brand-logo-car-symbol-with-name-black-design-japan-automobile-illustration-free-vector.jpg",
                            IsDeleted = false,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://e7.pngegg.com/pngimages/113/140/png-clipart-ford-motor-company-car-ford-f-series-ford-mondeo-auto-parts-emblem-logo-thumbnail.png",
                            IsDeleted = false,
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://i.pinimg.com/736x/d2/59/dc/d259dcd272a3ca9b538e68aedf721fb3.jpg",
                            IsDeleted = false,
                            Name = "Chevrolet"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQRVqlZCGRqalei2z79Kc3CzWKWkvb9p1U0A&s",
                            IsDeleted = false,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://uploads.audi-mediacenter.com/system/production/media/1282/images/bde751ee18fe149036c6b47d7595f6784f8901f8/AL090142_web_2880.jpg?1698171883",
                            IsDeleted = false,
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://thumbs.dreamstime.com/b/web-136350849.jpg",
                            IsDeleted = false,
                            Name = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/08/15/18/18/honda-1596081_640.png",
                            IsDeleted = false,
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "https://wieck-nissanao-production.s3.amazonaws.com/photos/87dd7b734e373e65761492bd446b20efd0a56737/thumbnail-364x204.jpg",
                            IsDeleted = false,
                            Name = "Nissan"
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_bLDZ_uRSEueAUuNQjCnwIJKe7Ml71Kq66g&s",
                            IsDeleted = false,
                            Name = "Hyundai"
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "https://static.vecteezy.com/system/resources/previews/020/500/396/non_2x/kia-logo-brand-symbol-black-design-south-korean-car-automobile-illustration-free-vector.jpg",
                            IsDeleted = false,
                            Name = "Kia"
                        });
                });

            modelBuilder.Entity("CarDealershipApp.Data.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ListedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ModelId");

                    b.HasIndex("SellerId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CarDealershipApp.Data.Models.CarFeature", b =>
                {
                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.HasKey("CarId", "FeatureId");

                    b.HasIndex("FeatureId");

                    b.ToTable("CarsFeatures");
                });

            modelBuilder.Entity("CarDealershipApp.Data.Models.CarImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("CarsImages");
                });

            modelBuilder.Entity("CarDealershipApp.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sedan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "SUV"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pickup Truck"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Wagon"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mini-Van"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Hatchback"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Convertible"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Coupé"
                        });
                });

            modelBuilder.Entity("CarDealershipApp.Data.Models.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sunroof"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Leather Seats"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Backup Camera"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bluetooth Connectivity"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Navigation System"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Blind Spot Monitoring"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Heated Seats"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Remote Start"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Parking Sensors"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Apple CarPlay"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Alloy Wheels"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Adaptive Cruise Control"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Power Liftgate"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Third-Row Seating"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Tow Package"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Keyless Entry"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Rain-Sensing Wipers"
                        },
                        new
                        {
                            Id = 18,
                            Name = "USB Charging Ports"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Smart Key Technology"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Rear Cross-Traffic Alert"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Wireless Phone Charging"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Surround Sound System"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Dynamic Traction Control"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Active Lane Keeping Assist"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Performance Exhaust System"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Adaptive Headlights"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Privacy Glass"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Dual-Zone Climate Control"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Fog Lights"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Ventilated Seats"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Android Auto"
                        });
                });

            modelBuilder.Entity("CarDealershipApp.Data.Models.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            IsDeleted = false,
                            Name = "Corolla"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            IsDeleted = false,
                            Name = "Camry"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            IsDeleted = false,
                            Name = "RAV4"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 1,
                            IsDeleted = false,
                            Name = "Land Cruiser"
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 1,
                            IsDeleted = false,
                            Name = "Highlander"
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 1,
                            IsDeleted = false,
                            Name = "Tacoma"
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 2,
                            IsDeleted = false,
                            Name = "Focus"
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 2,
                            IsDeleted = false,
                            Name = "Mustang"
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 2,
                            IsDeleted = false,
                            Name = "F-150"
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 2,
                            IsDeleted = false,
                            Name = "Explorer"
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 2,
                            IsDeleted = false,
                            Name = "Fusion"
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 2,
                            IsDeleted = false,
                            Name = "Edge"
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 3,
                            IsDeleted = false,
                            Name = "Malibu"
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 3,
                            IsDeleted = false,
                            Name = "Impala"
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 3,
                            IsDeleted = false,
                            Name = "Tahoe"
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 3,
                            IsDeleted = false,
                            Name = "Camaro"
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 3,
                            IsDeleted = false,
                            Name = "Equinox"
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 3,
                            IsDeleted = false,
                            Name = "Suburban"
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 4,
                            IsDeleted = false,
                            Name = "3 Series"
                        },
                        new
                        {
                            Id = 21,
                            BrandId = 4,
                            IsDeleted = false,
                            Name = "X5"
                        },
                        new
                        {
                            Id = 22,
                            BrandId = 4,
                            IsDeleted = false,
                            Name = "M3"
                        },
                        new
                        {
                            Id = 23,
                            BrandId = 4,
                            IsDeleted = false,
                            Name = "5 Series"
                        },
                        new
                        {
                            Id = 24,
                            BrandId = 4,
                            IsDeleted = false,
                            Name = "X3"
                        },
                        new
                        {
                            Id = 25,
                            BrandId = 4,
                            IsDeleted = false,
                            Name = "7 Series"
                        },
                        new
                        {
                            Id = 26,
                            BrandId = 5,
                            IsDeleted = false,
                            Name = "A4"
                        },
                        new
                        {
                            Id = 27,
                            BrandId = 5,
                            IsDeleted = false,
                            Name = "Q7"
                        },
                        new
                        {
                            Id = 28,
                            BrandId = 5,
                            IsDeleted = false,
                            Name = "A6"
                        },
                        new
                        {
                            Id = 29,
                            BrandId = 5,
                            IsDeleted = false,
                            Name = "Q5"
                        },
                        new
                        {
                            Id = 30,
                            BrandId = 5,
                            IsDeleted = false,
                            Name = "A3"
                        },
                        new
                        {
                            Id = 31,
                            BrandId = 5,
                            IsDeleted = false,
                            Name = "Q3"
                        },
                        new
                        {
                            Id = 32,
                            BrandId = 6,
                            IsDeleted = false,
                            Name = "C-Class"
                        },
                        new
                        {
                            Id = 33,
                            BrandId = 6,
                            IsDeleted = false,
                            Name = "E-Class"
                        },
                        new
                        {
                            Id = 34,
                            BrandId = 6,
                            IsDeleted = false,
                            Name = "S-Class"
                        },
                        new
                        {
                            Id = 35,
                            BrandId = 6,
                            IsDeleted = false,
                            Name = "GLC"
                        },
                        new
                        {
                            Id = 36,
                            BrandId = 6,
                            IsDeleted = false,
                            Name = "A-Class"
                        },
                        new
                        {
                            Id = 37,
                            BrandId = 6,
                            IsDeleted = false,
                            Name = "GLA"
                        },
                        new
                        {
                            Id = 38,
                            BrandId = 7,
                            IsDeleted = false,
                            Name = "Civic"
                        },
                        new
                        {
                            Id = 39,
                            BrandId = 7,
                            IsDeleted = false,
                            Name = "Accord"
                        },
                        new
                        {
                            Id = 40,
                            BrandId = 7,
                            IsDeleted = false,
                            Name = "CR-V"
                        },
                        new
                        {
                            Id = 41,
                            BrandId = 7,
                            IsDeleted = false,
                            Name = "Pilot"
                        },
                        new
                        {
                            Id = 42,
                            BrandId = 8,
                            IsDeleted = false,
                            Name = "Altima"
                        },
                        new
                        {
                            Id = 43,
                            BrandId = 8,
                            IsDeleted = false,
                            Name = "Maxima"
                        },
                        new
                        {
                            Id = 44,
                            BrandId = 8,
                            IsDeleted = false,
                            Name = "Murano"
                        },
                        new
                        {
                            Id = 45,
                            BrandId = 8,
                            IsDeleted = false,
                            Name = "Rogue"
                        },
                        new
                        {
                            Id = 46,
                            BrandId = 9,
                            IsDeleted = false,
                            Name = "Elantra"
                        },
                        new
                        {
                            Id = 47,
                            BrandId = 9,
                            IsDeleted = false,
                            Name = "Sonata"
                        },
                        new
                        {
                            Id = 48,
                            BrandId = 9,
                            IsDeleted = false,
                            Name = "Tucson"
                        },
                        new
                        {
                            Id = 49,
                            BrandId = 9,
                            IsDeleted = false,
                            Name = "Santa Fe"
                        },
                        new
                        {
                            Id = 50,
                            BrandId = 10,
                            IsDeleted = false,
                            Name = "Forte"
                        },
                        new
                        {
                            Id = 51,
                            BrandId = 10,
                            IsDeleted = false,
                            Name = "Optima"
                        },
                        new
                        {
                            Id = 52,
                            BrandId = 10,
                            IsDeleted = false,
                            Name = "Sorento"
                        },
                        new
                        {
                            Id = 53,
                            BrandId = 10,
                            IsDeleted = false,
                            Name = "Sportage"
                        });
                });

            modelBuilder.Entity("CarDealershipApp.Data.Models.UserCar", b =>
                {
                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CarId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersCars");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "4e32b02a-046c-40be-bfeb-327c900e6bb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "919527f5-26a4-4b4b-98bf-3a11a2bc3a6e",
                            Email = "default@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DEFAULT@GMAIL.COM",
                            NormalizedUserName = "DEFAULT@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHHk7fyRDOFglYPSgeoyzDlZJpWEHq/73YYKwNJBpNODlvz0RG9bw1P3TUQKtBZrxg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "27f06256-ac71-4ff2-a99f-5364d5c67238",
                            TwoFactorEnabled = false,
                            UserName = "default@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CarDealershipApp.Data.Models.Car", b =>
                {
                    b.HasOne("CarDealershipApp.Data.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarDealershipApp.Data.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarDealershipApp.Data.Models.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Model");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("CarDealershipApp.Data.Models.CarFeature", b =>
                {
                    b.HasOne("CarDealershipApp.Data.Models.Car", "Car")
                        .WithMany("CarsFeatures")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarDealershipApp.Data.Models.Feature", "Feature")
                        .WithMany("CarsFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("CarDealershipApp.Data.Models.CarImage", b =>
                {
                    b.HasOne("CarDealershipApp.Data.Models.Car", "Car")
                        .WithMany("Images")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("CarDealershipApp.Data.Models.Model", b =>
                {
                    b.HasOne("CarDealershipApp.Data.Models.Brand", "Brand")
                        .WithMany("Models")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("CarDealershipApp.Data.Models.UserCar", b =>
                {
                    b.HasOne("CarDealershipApp.Data.Models.Car", "Car")
                        .WithMany("UsersCars")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarDealershipApp.Data.Models.Brand", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("CarDealershipApp.Data.Models.Car", b =>
                {
                    b.Navigation("CarsFeatures");

                    b.Navigation("Images");

                    b.Navigation("UsersCars");
                });

            modelBuilder.Entity("CarDealershipApp.Data.Models.Feature", b =>
                {
                    b.Navigation("CarsFeatures");
                });
#pragma warning restore 612, 618
        }
    }
}
